# yaml-language-server: $schema=./config.schema.json
template_markers:
  open: "✏️{"
  close: "}✏️"
templates:
  openstates-to-ocd-decentralized:
    folder-name: ✏️{locale}✏️-data-pipeline
locales:
  al:
    template: openstates-to-ocd-decentralized
    toolkit_branch: main # Switch the branch name
    text_extraction: false # Switch to true to enable text extraction
  ak:
    template: openstates-to-ocd-decentralized
  az:
    template: openstates-to-ocd-decentralized
  ar:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  ca:
    template: openstates-to-ocd-decentralized
  co:
    template: openstates-to-ocd-decentralized
  ct:
    template: openstates-to-ocd-decentralized
  de:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  fl:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  ga:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  hi:
    template: openstates-to-ocd-decentralized
  id:
    template: openstates-to-ocd-decentralized
  il:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  in:
    template: openstates-to-ocd-decentralized
  ia:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  ks:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  ky:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  la:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  me:
    template: openstates-to-ocd-decentralized
  md:
    template: openstates-to-ocd-decentralized
  ma:
    template: openstates-to-ocd-decentralized
  mi:
    template: openstates-to-ocd-decentralized
  mn:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  ms:
    template: openstates-to-ocd-decentralized
  mo:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  mt:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  ne:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  nv:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  nh:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  nj:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  nm:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  ny:
    template: openstates-to-ocd-decentralized
  nc:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  nd:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  oh:
    template: openstates-to-ocd-decentralized
  ok:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  or:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  pa:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  ri:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  sc:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  sd:
    template: openstates-to-ocd-decentralized
  tn:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  tx:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  ut:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  vt:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  va:
    template: openstates-to-ocd-decentralized
  wa:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  wv:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  wi:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  wy:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  pr:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  mp:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  vi:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  gu:
    template: openstates-to-ocd-decentralized
    labels:
      - working
  usa:
    template: openstates-to-ocd-decentralized
    labels:
      - working
